version: "3.5"
services:

  bootnode:
    image: ankrnetwork/bas-template-bsc:devel
    container_name: bootnode
    command:
      - "geth"
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--networkid=$CHAIN_ID"
      - "--nodekeyhex=a08c0d8bf5042b7435dd9c0c993cf64c131047494926c2725c72221be165294e"
      - "--nat=extip:$HOST_IP"
      - "--syncmode=full"
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./datadir/bootnode:/datadir/geth"
    network_mode: "host"
    ports:
      - "30303:30303"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: always

  validator_1:
    image: ankrnetwork/bas-template-bsc:devel
    container_name: validator_1
    command:
      - "geth"
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--unlock=0x389C759F5A432ec01DCd7806a210d00Fa022F129"
      - "--miner.etherbase=0x389C759F5A432ec01DCd7806a210d00Fa022F129"
      - "--bootnodes=enode://17bf6bc7a031020fc9d2c29336ff6c4c486e0f231f2b7bf8b713f5217c0adc1f7fa538b2c80c2a607e3de577d2f7db0b371b989e75b6f1ff6e236a066a2d8083@44.211.233.215:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--networkid=$CHAIN_ID"
      - "--nat=extip:$HOST_IP"
      - "--port=30304"
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./keystores/validator_1/keystore:/datadir/keystore"
      - "./genesis/password.txt:/datadir/password.txt"
      - "./datadir/validator_1:/datadir/geth"
    ports:
      - "30304:30304"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: always
  validator_2:
    image: ankrnetwork/bas-template-bsc:devel
    container_name: validator_2
    command:
      - "geth"
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--unlock=0xD036B2E4E4a0fE043F7abC564A84AA9E0d3b25f6"
      - "--miner.etherbase=0xD036B2E4E4a0fE043F7abC564A84AA9E0d3b25f6"
      - "--bootnodes=enode://17bf6bc7a031020fc9d2c29336ff6c4c486e0f231f2b7bf8b713f5217c0adc1f7fa538b2c80c2a607e3de577d2f7db0b371b989e75b6f1ff6e236a066a2d8083@44.211.233.215:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--networkid=$CHAIN_ID"
      - "--nat=extip:$HOST_IP"
      - "--port=30305"
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./keystores/validator_2/keystore:/datadir/keystore"
      - "./genesis/password.txt:/datadir/password.txt"
      - "./datadir/validator_2:/datadir/geth"
    ports:
      - "30305:30305"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: always
  validator_3:
    image: ankrnetwork/bas-template-bsc:devel
    container_name: validator_3
    command:
      - "geth"
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--mine"
      - "--password=/datadir/password.txt"
      - "--unlock=0x9d37cBfb0A2ffF9d863C6dEB024772431E110c6A"
      - "--miner.etherbase=0x9d37cBfb0A2ffF9d863C6dEB024772431E110c6A"
      - "--bootnodes=enode://17bf6bc7a031020fc9d2c29336ff6c4c486e0f231f2b7bf8b713f5217c0adc1f7fa538b2c80c2a607e3de577d2f7db0b371b989e75b6f1ff6e236a066a2d8083@44.211.233.215:30303"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--networkid=$CHAIN_ID"
      - "--nat=extip:$HOST_IP"
      - "--port=30306"
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./keystores/validator_3/keystore:/datadir/keystore"
      - "./genesis/password.txt:/datadir/password.txt"
      - "./datadir/validator_3:/datadir/geth"
    ports:
      - "30306:30306"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: always

  rpc:
    image: ankrnetwork/bas-template-bsc:devel
    container_name: rpc
    command:
      - "geth"
      - "--datadir=/datadir"
      - "--genesis=/datadir/genesis.json"
      - "--bootnodes=enode://17bf6bc7a031020fc9d2c29336ff6c4c486e0f231f2b7bf8b713f5217c0adc1f7fa538b2c80c2a607e3de577d2f7db0b371b989e75b6f1ff6e236a066a2d8083@44.211.233.215:30303"
      - "--networkid=$CHAIN_ID"
      - "--port=30307"
      - "--gcmode=archive"
      - "--syncmode=full"
      - "--http"
      - "--http.addr=0.0.0.0"
      - "--http.api=eth,net,web3,debug,trace,txpool"
      - "--http.port=8545"
      - "--http.corsdomain=*"
      - "--http.vhosts=*"
      - "--ws"
      - "--ws.addr=0.0.0.0"
      - "--ws.api=eth,net,web3,debug,trace,txpool"
      - "--ws.port=8546"
      - "--ws.origins=*"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - "./genesis.json:/datadir/genesis.json"
      - "./datadir/rpc:/datadir/geth"
    restart: always

  staking-ui:
    container_name: 'staking'
    image: ankrnetwork/bas-staking-ui:devel
    environment:
      REACT_APP_ENVIRONMENT: "production"
      CHAIN_ID: "${CHAIN_ID}"
      CHAIN_NAME: "${CHAIN_NAME}"
      CHAIN_RPC: "https://rpc.${DOMAIN_NAME}"
      EXPLORER_HOME_URL: "https://scan.${DOMAIN_NAME}/"
      EXPLORER_TX_URL: "https://scan.${DOMAIN_NAME}/tx/{tx}"
      EXPLORER_ADDRESS_URL: "https://scan.${DOMAIN_NAME}/address/{address}"
      EXPLORER_BLOCK_URL: "https://scan.${DOMAIN_NAME}/block/{block}"
      # new env
      REACT_APP_API_ENDPOINT: "https://rpc.${DOMAIN_NAME}"
      REACT_APP_DEFAULT_NETWORK: "${CHAIN_NAME}"
      REACT_APP_CHAIN_ID: "${CHAIN_ID}"
      REACT_APP_EXPLORER_URL: "https://scan.${DOMAIN_NAME}/"
      REACT_APP_CHAIN_NAME: "${CHAIN_NAME} #${CHAIN_ID}"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - "3001:80"
    restart: always

  nginx:
    build: "./nginx"
    container_name: "nginx"
    environment:
      DOMAIN_NAME: "${DOMAIN_NAME}"
    volumes:
      - ~/.acme.sh/:/root/.acme.sh/
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - "80:80"
      - "443:443"
    restart: always